# Generated by Django 5.1.3 on 2024-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("CR", "Curd"),
                    ("ML", "Milk"),
                    ("LS", "Lassi"),
                    ("MS", "Milkshake"),
                    ("PN", "Paneer"),
                    ("GH", "Ghee"),
                    ("CZ", "Cheese"),
                    ("IC", "Ice-Creams"),
                ],
                default="ML",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="prodapp",
            field=models.TextField(default=""),
        ),
    ]
