# Generated by Django 5.1.3 on 2024-12-03 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_payment_orderplaced"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderplaced",
            old_name="ordered_date",
            new_name="ordered_data",
        ),
    ]
